// Seed data for global keywords organized by category
export const seedKeywords = [
  // PLUMBING
  { keyword: 'plumber near me', category: 'plumbing', search_volume: 74000, competition: 'high', cpc: 15.50 },
  { keyword: 'emergency plumber', category: 'plumbing', search_volume: 33100, competition: 'high', cpc: 18.75 },
  { keyword: 'water heater repair', category: 'plumbing', search_volume: 27100, competition: 'medium', cpc: 12.30 },
  { keyword: 'drain cleaning service', category: 'plumbing', search_volume: 18100, competition: 'medium', cpc: 10.50 },
  { keyword: 'leak detection', category: 'plumbing', search_volume: 14800, competition: 'medium', cpc: 11.20 },
  { keyword: 'plumbing repair', category: 'plumbing', search_volume: 12100, competition: 'high', cpc: 13.40 },
  { keyword: 'sewer line repair', category: 'plumbing', search_volume: 9900, competition: 'medium', cpc: 14.60 },
  { keyword: 'water line replacement', category: 'plumbing', search_volume: 8100, competition: 'low', cpc: 9.80 },
  { keyword: 'toilet repair', category: 'plumbing', search_volume: 6600, competition: 'low', cpc: 7.50 },
  { keyword: 'faucet installation', category: 'plumbing', search_volume: 5400, competition: 'low', cpc: 6.20 },

  // HVAC
  { keyword: 'hvac near me', category: 'hvac', search_volume: 60500, competition: 'high', cpc: 16.80 },
  { keyword: 'air conditioning repair', category: 'hvac', search_volume: 49500, competition: 'high', cpc: 19.50 },
  { keyword: 'furnace repair', category: 'hvac', search_volume: 33100, competition: 'high', cpc: 17.30 },
  { keyword: 'hvac installation', category: 'hvac', search_volume: 27100, competition: 'medium', cpc: 15.60 },
  { keyword: 'ac repair', category: 'hvac', search_volume: 22200, competition: 'high', cpc: 18.20 },
  { keyword: 'heating and cooling', category: 'hvac', search_volume: 18100, competition: 'medium', cpc: 14.70 },
  { keyword: 'air duct cleaning', category: 'hvac', search_volume: 14800, competition: 'medium', cpc: 11.90 },
  { keyword: 'hvac maintenance', category: 'hvac', search_volume: 12100, competition: 'low', cpc: 10.50 },
  { keyword: 'central air installation', category: 'hvac', search_volume: 9900, competition: 'medium', cpc: 16.40 },
  { keyword: 'furnace installation', category: 'hvac', search_volume: 8100, competition: 'medium', cpc: 15.80 },

  // ELECTRICIAN
  { keyword: 'electrician near me', category: 'electrician', search_volume: 90500, competition: 'high', cpc: 17.20 },
  { keyword: 'emergency electrician', category: 'electrician', search_volume: 40500, competition: 'high', cpc: 20.50 },
  { keyword: 'electrical repair', category: 'electrician', search_volume: 22200, competition: 'medium', cpc: 14.80 },
  { keyword: 'panel upgrade', category: 'electrician', search_volume: 12100, competition: 'medium', cpc: 13.60 },
  { keyword: 'outlet installation', category: 'electrician', search_volume: 9900, competition: 'low', cpc: 9.40 },
  { keyword: 'lighting installation', category: 'electrician', search_volume: 18100, competition: 'medium', cpc: 11.70 },
  { keyword: 'ceiling fan installation', category: 'electrician', search_volume: 14800, competition: 'low', cpc: 8.90 },
  { keyword: 'electrical wiring', category: 'electrician', search_volume: 8100, competition: 'medium', cpc: 12.30 },
  { keyword: 'circuit breaker replacement', category: 'electrician', search_volume: 6600, competition: 'low', cpc: 10.80 },
  { keyword: 'generator installation', category: 'electrician', search_volume: 5400, competition: 'medium', cpc: 15.20 },

  // ROOFING
  { keyword: 'roofer near me', category: 'roofing', search_volume: 74000, competition: 'high', cpc: 22.50 },
  { keyword: 'roof repair', category: 'roofing', search_volume: 60500, competition: 'high', cpc: 21.80 },
  { keyword: 'roof replacement', category: 'roofing', search_volume: 49500, competition: 'high', cpc: 24.30 },
  { keyword: 'emergency roof repair', category: 'roofing', search_volume: 22200, competition: 'medium', cpc: 23.70 },
  { keyword: 'roof leak repair', category: 'roofing', search_volume: 18100, competition: 'medium', cpc: 19.50 },
  { keyword: 'roof inspection', category: 'roofing', search_volume: 14800, competition: 'low', cpc: 12.40 },
  { keyword: 'shingle replacement', category: 'roofing', search_volume: 12100, competition: 'medium', cpc: 18.60 },
  { keyword: 'flat roof repair', category: 'roofing', search_volume: 9900, competition: 'low', cpc: 16.80 },
  { keyword: 'gutter installation', category: 'roofing', search_volume: 8100, competition: 'low', cpc: 11.20 },
  { keyword: 'roof maintenance', category: 'roofing', search_volume: 6600, competition: 'low', cpc: 10.50 },

  // LANDSCAPING
  { keyword: 'landscaping near me', category: 'landscaping', search_volume: 90500, competition: 'high', cpc: 8.90 },
  { keyword: 'lawn care service', category: 'landscaping', search_volume: 74000, competition: 'high', cpc: 9.50 },
  { keyword: 'tree removal', category: 'landscaping', search_volume: 60500, competition: 'medium', cpc: 12.70 },
  { keyword: 'landscape design', category: 'landscaping', search_volume: 33100, competition: 'medium', cpc: 11.40 },
  { keyword: 'lawn mowing service', category: 'landscaping', search_volume: 27100, competition: 'medium', cpc: 7.80 },
  { keyword: 'irrigation installation', category: 'landscaping', search_volume: 14800, competition: 'low', cpc: 10.30 },
  { keyword: 'mulching service', category: 'landscaping', search_volume: 12100, competition: 'low', cpc: 6.50 },
  { keyword: 'sod installation', category: 'landscaping', search_volume: 9900, competition: 'low', cpc: 8.20 },
  { keyword: 'hedge trimming', category: 'landscaping', search_volume: 8100, competition: 'low', cpc: 5.90 },
  { keyword: 'lawn aeration', category: 'landscaping', search_volume: 6600, competition: 'low', cpc: 7.10 },

  // LOCKSMITH
  { keyword: 'locksmith near me', category: 'locksmith', search_volume: 110000, competition: 'high', cpc: 14.20 },
  { keyword: 'emergency locksmith', category: 'locksmith', search_volume: 49500, competition: 'high', cpc: 16.80 },
  { keyword: 'car locksmith', category: 'locksmith', search_volume: 33100, competition: 'high', cpc: 15.50 },
  { keyword: 'lock change', category: 'locksmith', search_volume: 22200, competition: 'medium', cpc: 12.30 },
  { keyword: 'rekey locks', category: 'locksmith', search_volume: 14800, competition: 'medium', cpc: 11.60 },
  { keyword: 'lock installation', category: 'locksmith', search_volume: 12100, competition: 'low', cpc: 10.40 },
  { keyword: 'safe opening', category: 'locksmith', search_volume: 8100, competition: 'low', cpc: 13.70 },
  { keyword: 'deadbolt installation', category: 'locksmith', search_volume: 6600, competition: 'low', cpc: 9.80 },
  { keyword: 'key duplication', category: 'locksmith', search_volume: 5400, competition: 'low', cpc: 6.20 },
  { keyword: 'lock repair', category: 'locksmith', search_volume: 4400, competition: 'low', cpc: 8.50 },

  // CLEANING
  { keyword: 'cleaning service near me', category: 'cleaning', search_volume: 135000, competition: 'high', cpc: 9.20 },
  { keyword: 'house cleaning', category: 'cleaning', search_volume: 90500, competition: 'high', cpc: 10.50 },
  { keyword: 'maid service', category: 'cleaning', search_volume: 74000, competition: 'high', cpc: 11.30 },
  { keyword: 'carpet cleaning', category: 'cleaning', search_volume: 60500, competition: 'medium', cpc: 8.90 },
  { keyword: 'office cleaning', category: 'cleaning', search_volume: 40500, competition: 'medium', cpc: 7.60 },
  { keyword: 'deep cleaning service', category: 'cleaning', search_volume: 33100, competition: 'medium', cpc: 9.80 },
  { keyword: 'move out cleaning', category: 'cleaning', search_volume: 27100, competition: 'low', cpc: 8.40 },
  { keyword: 'window cleaning', category: 'cleaning', search_volume: 22200, competition: 'low', cpc: 6.70 },
  { keyword: 'pressure washing', category: 'cleaning', search_volume: 18100, competition: 'low', cpc: 7.80 },
  { keyword: 'tile and grout cleaning', category: 'cleaning', search_volume: 12100, competition: 'low', cpc: 6.20 },

  // PEST CONTROL
  { keyword: 'pest control near me', category: 'pest_control', search_volume: 90500, competition: 'high', cpc: 11.50 },
  { keyword: 'exterminator', category: 'pest_control', search_volume: 74000, competition: 'high', cpc: 12.80 },
  { keyword: 'termite inspection', category: 'pest_control', search_volume: 40500, competition: 'medium', cpc: 14.30 },
  { keyword: 'bed bug treatment', category: 'pest_control', search_volume: 33100, competition: 'medium', cpc: 13.70 },
  { keyword: 'rodent control', category: 'pest_control', search_volume: 22200, competition: 'medium', cpc: 10.90 },
  { keyword: 'ant control', category: 'pest_control', search_volume: 18100, competition: 'low', cpc: 8.60 },
  { keyword: 'mosquito control', category: 'pest_control', search_volume: 14800, competition: 'low', cpc: 9.40 },
  { keyword: 'wildlife removal', category: 'pest_control', search_volume: 12100, competition: 'low', cpc: 11.20 },
  { keyword: 'cockroach extermination', category: 'pest_control', search_volume: 9900, competition: 'low', cpc: 10.50 },
  { keyword: 'flea treatment', category: 'pest_control', search_volume: 8100, competition: 'low', cpc: 8.80 },

  // GENERAL CONTRACTOR
  { keyword: 'general contractor near me', category: 'general_contractor', search_volume: 60500, competition: 'high', cpc: 16.40 },
  { keyword: 'home remodeling', category: 'general_contractor', search_volume: 49500, competition: 'high', cpc: 18.70 },
  { keyword: 'bathroom remodel', category: 'general_contractor', search_volume: 40500, competition: 'high', cpc: 19.50 },
  { keyword: 'kitchen remodel', category: 'general_contractor', search_volume: 33100, competition: 'high', cpc: 21.30 },
  { keyword: 'home addition', category: 'general_contractor', search_volume: 22200, competition: 'medium', cpc: 17.80 },
  { keyword: 'basement finishing', category: 'general_contractor', search_volume: 18100, competition: 'medium', cpc: 15.60 },
  { keyword: 'deck builder', category: 'general_contractor', search_volume: 14800, competition: 'medium', cpc: 14.20 },
  { keyword: 'home renovation', category: 'general_contractor', search_volume: 12100, competition: 'medium', cpc: 16.90 },
  { keyword: 'flooring installation', category: 'general_contractor', search_volume: 9900, competition: 'low', cpc: 12.40 },
  { keyword: 'drywall repair', category: 'general_contractor', search_volume: 8100, competition: 'low', cpc: 9.80 },

  // DENTIST
  { keyword: 'dentist near me', category: 'dentist', search_volume: 246000, competition: 'high', cpc: 8.90 },
  { keyword: 'emergency dentist', category: 'dentist', search_volume: 90500, competition: 'high', cpc: 11.50 },
  { keyword: 'teeth cleaning', category: 'dentist', search_volume: 60500, competition: 'medium', cpc: 7.60 },
  { keyword: 'teeth whitening', category: 'dentist', search_volume: 49500, competition: 'high', cpc: 9.80 },
  { keyword: 'dental implants', category: 'dentist', search_volume: 40500, competition: 'high', cpc: 12.30 },
  { keyword: 'root canal', category: 'dentist', search_volume: 33100, competition: 'medium', cpc: 10.70 },
  { keyword: 'invisalign', category: 'dentist', search_volume: 27100, competition: 'high', cpc: 13.40 },
  { keyword: 'wisdom teeth removal', category: 'dentist', search_volume: 22200, competition: 'medium', cpc: 11.90 },
  { keyword: 'dental crown', category: 'dentist', search_volume: 18100, competition: 'low', cpc: 9.50 },
  { keyword: 'cosmetic dentistry', category: 'dentist', search_volume: 14800, competition: 'medium', cpc: 10.20 },

  // HEALTHCARE
  { keyword: 'doctor near me', category: 'healthcare', search_volume: 301000, competition: 'high', cpc: 7.80 },
  { keyword: 'urgent care near me', category: 'healthcare', search_volume: 165000, competition: 'high', cpc: 9.50 },
  { keyword: 'physical therapy', category: 'healthcare', search_volume: 90500, competition: 'high', cpc: 11.20 },
  { keyword: 'chiropractor near me', category: 'healthcare', search_volume: 74000, competition: 'high', cpc: 10.40 },
  { keyword: 'dermatologist', category: 'healthcare', search_volume: 60500, competition: 'high', cpc: 12.80 },
  { keyword: 'pediatrician near me', category: 'healthcare', search_volume: 49500, competition: 'medium', cpc: 8.60 },
  { keyword: 'mental health counseling', category: 'healthcare', search_volume: 40500, competition: 'medium', cpc: 13.70 },
  { keyword: 'orthopedic surgeon', category: 'healthcare', search_volume: 33100, competition: 'medium', cpc: 14.90 },
  { keyword: 'family medicine', category: 'healthcare', search_volume: 27100, competition: 'low', cpc: 7.20 },
  { keyword: 'massage therapy', category: 'healthcare', search_volume: 22200, competition: 'medium', cpc: 9.30 },

  // EDUCATION
  { keyword: 'tutoring near me', category: 'education', search_volume: 74000, competition: 'medium', cpc: 8.50 },
  { keyword: 'online courses', category: 'education', search_volume: 135000, competition: 'high', cpc: 12.30 },
  { keyword: 'music lessons', category: 'education', search_volume: 60500, competition: 'low', cpc: 6.70 },
  { keyword: 'driving school', category: 'education', search_volume: 49500, competition: 'medium', cpc: 9.80 },
  { keyword: 'language classes', category: 'education', search_volume: 40500, competition: 'medium', cpc: 10.20 },
  { keyword: 'preschool near me', category: 'education', search_volume: 33100, competition: 'medium', cpc: 11.50 },
  { keyword: 'test prep tutoring', category: 'education', search_volume: 27100, competition: 'high', cpc: 15.40 },
  { keyword: 'coding bootcamp', category: 'education', search_volume: 22200, competition: 'high', cpc: 18.60 },
  { keyword: 'art classes', category: 'education', search_volume: 18100, competition: 'low', cpc: 7.90 },
  { keyword: 'dance lessons', category: 'education', search_volume: 14800, competition: 'low', cpc: 6.80 },

  // REAL ESTATE
  { keyword: 'real estate agent near me', category: 'real_estate', search_volume: 110000, competition: 'high', cpc: 14.80 },
  { keyword: 'homes for sale', category: 'real_estate', search_volume: 246000, competition: 'high', cpc: 16.50 },
  { keyword: 'apartments for rent', category: 'real_estate', search_volume: 201000, competition: 'high', cpc: 12.30 },
  { keyword: 'property management', category: 'real_estate', search_volume: 60500, competition: 'medium', cpc: 13.70 },
  { keyword: 'commercial real estate', category: 'real_estate', search_volume: 49500, competition: 'medium', cpc: 18.90 },
  { keyword: 'home appraisal', category: 'real_estate', search_volume: 40500, competition: 'low', cpc: 11.40 },
  { keyword: 'house buying', category: 'real_estate', search_volume: 33100, competition: 'high', cpc: 15.20 },
  { keyword: 'real estate investing', category: 'real_estate', search_volume: 27100, competition: 'medium', cpc: 17.60 },
  { keyword: 'luxury homes', category: 'real_estate', search_volume: 22200, competition: 'medium', cpc: 19.80 },
  { keyword: 'foreclosure listings', category: 'real_estate', search_volume: 18100, competition: 'low', cpc: 10.90 },

  // RETAIL
  { keyword: 'clothing store near me', category: 'retail', search_volume: 90500, competition: 'medium', cpc: 6.80 },
  { keyword: 'furniture store', category: 'retail', search_volume: 74000, competition: 'medium', cpc: 8.90 },
  { keyword: 'jewelry store', category: 'retail', search_volume: 60500, competition: 'medium', cpc: 11.20 },
  { keyword: 'shoe store near me', category: 'retail', search_volume: 49500, competition: 'low', cpc: 5.40 },
  { keyword: 'electronics store', category: 'retail', search_volume: 40500, competition: 'medium', cpc: 7.60 },
  { keyword: 'home decor store', category: 'retail', search_volume: 33100, competition: 'low', cpc: 6.20 },
  { keyword: 'sporting goods store', category: 'retail', search_volume: 27100, competition: 'low', cpc: 5.80 },
  { keyword: 'bookstore near me', category: 'retail', search_volume: 22200, competition: 'low', cpc: 4.90 },
  { keyword: 'toy store', category: 'retail', search_volume: 18100, competition: 'low', cpc: 5.50 },
  { keyword: 'pet supply store', category: 'retail', search_volume: 14800, competition: 'low', cpc: 6.70 },

  // LEGAL SERVICES
  { keyword: 'lawyer near me', category: 'legal_services', search_volume: 135000, competition: 'high', cpc: 28.50 },
  { keyword: 'personal injury attorney', category: 'legal_services', search_volume: 90500, competition: 'high', cpc: 42.80 },
  { keyword: 'divorce lawyer', category: 'legal_services', search_volume: 74000, competition: 'high', cpc: 35.60 },
  { keyword: 'criminal defense attorney', category: 'legal_services', search_volume: 60500, competition: 'high', cpc: 38.90 },
  { keyword: 'family law attorney', category: 'legal_services', search_volume: 49500, competition: 'medium', cpc: 32.40 },
  { keyword: 'estate planning attorney', category: 'legal_services', search_volume: 40500, competition: 'medium', cpc: 29.70 },
  { keyword: 'bankruptcy lawyer', category: 'legal_services', search_volume: 33100, competition: 'high', cpc: 36.20 },
  { keyword: 'immigration lawyer', category: 'legal_services', search_volume: 27100, competition: 'medium', cpc: 31.50 },
  { keyword: 'business attorney', category: 'legal_services', search_volume: 22200, competition: 'medium', cpc: 34.80 },
  { keyword: 'real estate attorney', category: 'legal_services', search_volume: 18100, competition: 'low', cpc: 27.30 },

  // HOSPITALITY
  { keyword: 'hotel near me', category: 'hospitality', search_volume: 301000, competition: 'high', cpc: 5.90 },
  { keyword: 'restaurant near me', category: 'hospitality', search_volume: 450000, competition: 'high', cpc: 4.80 },
  { keyword: 'catering service', category: 'hospitality', search_volume: 74000, competition: 'medium', cpc: 9.70 },
  { keyword: 'event venue', category: 'hospitality', search_volume: 60500, competition: 'medium', cpc: 11.20 },
  { keyword: 'wedding venue', category: 'hospitality', search_volume: 49500, competition: 'high', cpc: 13.80 },
  { keyword: 'banquet hall', category: 'hospitality', search_volume: 33100, competition: 'low', cpc: 8.50 },
  { keyword: 'bed and breakfast', category: 'hospitality', search_volume: 27100, competition: 'low', cpc: 6.30 },
  { keyword: 'bar near me', category: 'hospitality', search_volume: 22200, competition: 'medium', cpc: 5.40 },
  { keyword: 'coffee shop near me', category: 'hospitality', search_volume: 18100, competition: 'low', cpc: 4.20 },
  { keyword: 'food truck catering', category: 'hospitality', search_volume: 14800, competition: 'low', cpc: 7.60 },

  // E-COMMERCE
  { keyword: 'online shopping', category: 'ecommerce', search_volume: 823000, competition: 'high', cpc: 3.80 },
  { keyword: 'buy online', category: 'ecommerce', search_volume: 301000, competition: 'high', cpc: 4.50 },
  { keyword: 'dropshipping', category: 'ecommerce', search_volume: 135000, competition: 'high', cpc: 8.90 },
  { keyword: 'ecommerce platform', category: 'ecommerce', search_volume: 74000, competition: 'medium', cpc: 12.60 },
  { keyword: 'online marketplace', category: 'ecommerce', search_volume: 49500, competition: 'medium', cpc: 10.40 },
  { keyword: 'shopify store', category: 'ecommerce', search_volume: 40500, competition: 'high', cpc: 15.80 },
  { keyword: 'woocommerce', category: 'ecommerce', search_volume: 33100, competition: 'medium', cpc: 11.70 },
  { keyword: 'amazon fba', category: 'ecommerce', search_volume: 27100, competition: 'high', cpc: 13.20 },
  { keyword: 'digital products', category: 'ecommerce', search_volume: 22200, competition: 'low', cpc: 9.50 },
  { keyword: 'print on demand', category: 'ecommerce', search_volume: 18100, competition: 'medium', cpc: 10.80 },

  // AUTOMOTIVE
  { keyword: 'auto repair near me', category: 'automotive', search_volume: 135000, competition: 'high', cpc: 12.40 },
  { keyword: 'car dealership', category: 'automotive', search_volume: 110000, competition: 'high', cpc: 16.80 },
  { keyword: 'oil change near me', category: 'automotive', search_volume: 90500, competition: 'high', cpc: 11.20 },
  { keyword: 'tire shop', category: 'automotive', search_volume: 74000, competition: 'medium', cpc: 10.60 },
  { keyword: 'auto body shop', category: 'automotive', search_volume: 60500, competition: 'medium', cpc: 13.50 },
  { keyword: 'car detailing', category: 'automotive', search_volume: 49500, competition: 'low', cpc: 8.90 },
  { keyword: 'mechanic near me', category: 'automotive', search_volume: 40500, competition: 'high', cpc: 11.80 },
  { keyword: 'transmission repair', category: 'automotive', search_volume: 33100, competition: 'medium', cpc: 14.70 },
  { keyword: 'brake repair', category: 'automotive', search_volume: 27100, competition: 'low', cpc: 9.40 },
  { keyword: 'car wash near me', category: 'automotive', search_volume: 22200, competition: 'low', cpc: 6.80 },

  // JUNK REMOVAL & HAULING
  { keyword: 'junk removal & hauling', category: 'junk_removal', search_volume: 50, competition: 'unknown', cpc: 0.00 },
  { keyword: 'junk removal near me', category: 'junk_removal', search_volume: 500, competition: 'high', cpc: 15.09 },
  { keyword: 'junk haulers near me', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 14.43 },
  { keyword: 'junk pickup near me', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 11.74 },
  { keyword: 'junk pickup', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 13.48 },
  { keyword: 'haul away service', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 0.00 },
  { keyword: 'hauling services', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 12.66 },
  { keyword: 'junk removal services', category: 'junk_removal', search_volume: 500, competition: 'low', cpc: 11.14 },
  { keyword: 'hauling services near me', category: 'junk_removal', search_volume: 50, competition: 'medium', cpc: 0.00 },
  { keyword: 'junk hauling', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 0.00 },
  { keyword: 'cheap junk removal', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 7.38 },
  { keyword: 'we haul junk', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 0.00 },
  { keyword: 'trash hauling near me', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 14.43 },
  { keyword: 'haul junk away', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 14.93 },
  { keyword: 'cheapest junk removal near me', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 17.35 },
  { keyword: 'haul away junk removal', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 10.80 },
  { keyword: 'junk removal companies near me', category: 'junk_removal', search_volume: 50, competition: 'low', cpc: 0.00 },
  { keyword: 'junk removal service near me', category: 'junk_removal', search_volume: 50, competition: 'low', cpc: 0.00 },
  { keyword: 'cheapest junk haulers', category: 'junk_removal', search_volume: 0, competition: 'unknown', cpc: 0.00 },
  { keyword: 'haul away junk near me', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 0.00 },
  { keyword: 'junk pick up service', category: 'junk_removal', search_volume: 50, competition: 'unknown', cpc: 0.00 },
  { keyword: 'got junk pick up', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 0.00 },
  { keyword: 'same day junk removal near me', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 0.00 },
  { keyword: 'junk removal company', category: 'junk_removal', search_volume: 50, competition: 'low', cpc: 0.00 },
  { keyword: 'junk hauling service', category: 'junk_removal', search_volume: 50, competition: 'unknown', cpc: 0.00 },
  { keyword: 'haul away old furniture', category: 'junk_removal', search_volume: 50, competition: 'unknown', cpc: 0.00 },
  { keyword: 'we pick up junk', category: 'junk_removal', search_volume: 50, competition: 'unknown', cpc: 0.00 },
  { keyword: 'best junk removal near me', category: 'junk_removal', search_volume: 50, competition: 'medium', cpc: 0.00 },
  { keyword: 'trash hauling', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 0.00 },
  { keyword: 'mattress removal service', category: 'junk_removal', search_volume: 50, competition: 'low', cpc: 0.00 },
  { keyword: 'haul off junk', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 9.60 },
  { keyword: 'junk removal prices near me', category: 'junk_removal', search_volume: 50, competition: 'unknown', cpc: 0.00 },
  { keyword: 'junk away', category: 'junk_removal', search_volume: 50, competition: 'low', cpc: 0.00 },
  { keyword: 'trash haul away', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 0.00 },
  { keyword: 'haul my junk away', category: 'junk_removal', search_volume: 50, competition: 'unknown', cpc: 0.00 },
  { keyword: 'take my junk away', category: 'junk_removal', search_volume: 0, competition: 'unknown', cpc: 0.00 },
  { keyword: 'haul away service near me', category: 'junk_removal', search_volume: 50, competition: 'unknown', cpc: 0.00 },
  { keyword: 'junk hauling services near me', category: 'junk_removal', search_volume: 50, competition: 'medium', cpc: 15.11 },
  { keyword: 'furniture haul away service', category: 'junk_removal', search_volume: 50, competition: 'unknown', cpc: 0.00 },
  { keyword: 'junk haulers in my area', category: 'junk_removal', search_volume: 50, competition: 'unknown', cpc: 0.00 },
  { keyword: 'pick up junk furniture', category: 'junk_removal', search_volume: 50, competition: 'unknown', cpc: 0.00 },
  { keyword: 'hauling junk removal', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 0.00 },
  { keyword: 'you got junk pick up', category: 'junk_removal', search_volume: 50, competition: 'high', cpc: 0.00 },
  { keyword: 'hauling companies near me', category: 'junk_removal', search_volume: 50, competition: 'unknown', cpc: 0.00 },
  { keyword: 'haul off junk near me', category: 'junk_removal', search_volume: 50, competition: 'medium', cpc: 0.00 },
  { keyword: 'home junk removal', category: 'junk_removal', search_volume: 50, competition: 'unknown', cpc: 0.00 },
];

export const businessCategories = [
  { id: 'plumbing', name: 'Plumbing', avgJobValue: 350, conversionRate: 0.08 },
  { id: 'hvac', name: 'HVAC', avgJobValue: 450, conversionRate: 0.07 },
  { id: 'electrician', name: 'Electrician', avgJobValue: 300, conversionRate: 0.09 },
  { id: 'roofing', name: 'Roofing', avgJobValue: 800, conversionRate: 0.06 },
  { id: 'landscaping', name: 'Landscaping', avgJobValue: 250, conversionRate: 0.10 },
  { id: 'locksmith', name: 'Locksmith', avgJobValue: 150, conversionRate: 0.12 },
  { id: 'cleaning', name: 'Cleaning', avgJobValue: 120, conversionRate: 0.15 },
  { id: 'pest_control', name: 'Pest Control', avgJobValue: 200, conversionRate: 0.10 },
  { id: 'general_contractor', name: 'General Contractor', avgJobValue: 1200, conversionRate: 0.05 },
  { id: 'dentist', name: 'Dentist', avgJobValue: 280, conversionRate: 0.08 },
  { id: 'healthcare', name: 'Healthcare', avgJobValue: 350, conversionRate: 0.07 },
  { id: 'education', name: 'Education', avgJobValue: 180, conversionRate: 0.12 },
  { id: 'real_estate', name: 'Real Estate', avgJobValue: 2500, conversionRate: 0.03 },
  { id: 'retail', name: 'Retail', avgJobValue: 150, conversionRate: 0.18 },
  { id: 'legal_services', name: 'Legal Services', avgJobValue: 1500, conversionRate: 0.04 },
  { id: 'hospitality', name: 'Hospitality', avgJobValue: 250, conversionRate: 0.10 },
  { id: 'ecommerce', name: 'E-commerce', avgJobValue: 500, conversionRate: 0.05 },
  { id: 'automotive', name: 'Automotive', avgJobValue: 400, conversionRate: 0.08 },
  { id: 'junk_removal', name: 'Junk Removal & Hauling', avgJobValue: 100, conversionRate: 0.15 },
];